import fs from 'node:fs'
import path from 'node:path'
import type { SessionDiff } from './git.js'

export type AdrCandidate = {
  title: string
  context: string
  files: string[]
}

type AdrRule = {
  title: string
  context: string
  test: (file: string) => boolean
}

const ADR_RULES: AdrRule[] = [
  {
    title: '의존성 변경',
    context: 'package.json 또는 lockfile 변경 — 라이브러리 추가/교체 검토 필요',
    test: f => /package\.json$|pnpm-lock\.yaml$|package-lock\.json$|yarn\.lock$/.test(f),
  },
  {
    title: '빌드/도구 설정',
    context: '빌드·린트·테스트 설정 파일 변경',
    test: f => /\.(config|rc)\.(ts|js|mjs|cjs)$|tsconfig.*\.json$|vitest\.config|vite\.config|eslint|prettier/.test(f),
  },
  {
    title: '데이터베이스/스키마',
    context: 'DB 마이그레이션 또는 스키마 관련 파일 변경',
    test: f => /prisma\/|migrations\/|supabase\/|schema\.sql|drizzle/.test(f),
  },
  {
    title: '인프라/배포',
    context: 'Docker, CI, 배포 설정 변경',
    test: f => /Dockerfile|docker-compose|\.github\/workflows|vercel\.json|fly\.toml/.test(f),
  },
  {
    title: '인증/보안',
    context: '인증·권한·환경변수 템플릿 변경',
    test: f => /\.env\.example$|auth\/|middleware\.(ts|js)$/.test(f),
  },
]

export function detectAdrCandidates(diff: SessionDiff): AdrCandidate[] {
  const candidates: AdrCandidate[] = []

  for (const rule of ADR_RULES) {
    const matched = diff.files
      .map(f => f.file)
      .filter(rule.test)

    if (matched.length > 0) {
      candidates.push({
        title: rule.title,
        context: rule.context,
        files: matched,
      })
    }
  }

  return candidates
}

function nextAdrNumber(adrDir: string): number {
  if (!fs.existsSync(adrDir)) return 1

  const nums = fs.readdirSync(adrDir)
    .map(name => name.match(/^ADR-(\d+)/i)?.[1])
    .filter((n): n is string => Boolean(n))
    .map(n => parseInt(n, 10))

  return nums.length ? Math.max(...nums) + 1 : 1
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9가-힣-]/g, '')
    .slice(0, 40) || 'decision'
}

export function createAdrFile(
  cwd: string,
  title: string,
  context: string,
  decision: string,
  consequences: string
): string {
  const adrDir = path.join(cwd, 'docs', 'adr')
  if (!fs.existsSync(adrDir)) fs.mkdirSync(adrDir, { recursive: true })

  const num = nextAdrNumber(adrDir)
  const today = new Date().toISOString().split('T')[0]
  const fileName = `ADR-${String(num).padStart(3, '0')}-${slugify(title)}.md`
  const filePath = path.join(adrDir, fileName)

  const content = [
    '---',
    `id: ADR-${String(num).padStart(3, '0')}`,
    `date: ${today}`,
    'status: accepted',
    `tags: [${slugify(title)}]`,
    '---',
    '',
    `# ADR-${String(num).padStart(3, '0')}: ${title}`,
    '',
    '## 맥락 (Context)',
    context,
    '',
    '## 결정 (Decision)',
    decision,
    '',
    '## 대안 (Alternatives)',
    '_검토한 대안을 기록하세요._',
    '',
    '## 결과 (Consequences)',
    consequences,
    '',
    '---',
    `*Generated by \`vhk recap\` at ${new Date().toISOString()}*`,
  ].join('\n')

  fs.writeFileSync(filePath, content, 'utf-8')
  return filePath
}
