/**
 * RFC 0051 — recap 자동 트러블슈팅 문서를 TS-NNN 으로 채번 생성.
 * 기존 recap.ts 인라인은 `YYYY-MM-DD-제목.md` 라 수동 `TS-NNN` 과 모순이었다.
 * adr.ts 의 채번/slug 패턴을 복제해 ADR-NNN·TS-NNN 형식을 통일한다.
 */
import fs from 'node:fs'
import path from 'node:path'
import { localDate } from './date.js'

export function nextTsNumber(tsDir: string): number {
  if (!fs.existsSync(tsDir)) return 1

  const nums = fs.readdirSync(tsDir)
    .map(name => name.match(/^TS-(\d+)/i)?.[1])
    .filter((n): n is string => Boolean(n))
    .map(n => parseInt(n, 10))

  return nums.length ? Math.max(...nums) + 1 : 1
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9가-힣-]/g, '')
    .slice(0, 40) || 'issue'
}

export function createTroubleshootingFile(
  cwd: string,
  problem: string,
  cause: string,
  solution: string,
  commits: { hash: string; message: string }[],
): string {
  const tsDir = path.join(cwd, 'docs', 'troubleshooting')
  if (!fs.existsSync(tsDir)) fs.mkdirSync(tsDir, { recursive: true })

  const num = nextTsNumber(tsDir)
  const id = `TS-${String(num).padStart(3, '0')}`
  const today = localDate()
  const fileName = `${id}-${slugify(problem)}.md`
  const filePath = path.join(tsDir, fileName)

  const commitLines = commits.length
    ? commits.map(c => `- \`${c.hash.slice(0, 7)}\` ${c.message}`).join('\n')
    : '(연결된 커밋 없음)'

  const content = [
    '---',
    `id: ${id}`,
    `date: ${today}`,
    'category: build',
    '---',
    '',
    `# ${id} — ${problem}`,
    '',
    '## 증상',
    problem,
    '',
    '## 원인',
    cause,
    '',
    '## 해결',
    solution,
    '',
    '## 관련 커밋',
    commitLines,
    '',
    '---',
    `*Generated by \`vhk recap\` at ${new Date().toISOString()}*`,
  ].join('\n')

  fs.writeFileSync(filePath, content, 'utf-8')
  return filePath
}
