/**
 * @param opts.hasTest package.json 에 test 스크립트가 있으면 true.
 *   VHK-008: test 스크립트가 없는데 `pnpm test` 를 권하던 오안내 제거 — 없으면 build 만 안내.
 */
export function COMMANDS_MD_TEMPLATE(opts: { hasTest?: boolean } = {}): string {
  const buildTestRow = opts.hasTest
    ? '| 빌드+테스트 | `pnpm build; pnpm test --run` | "빌드하고 테스트 돌려" |'
    : '| 빌드 | `pnpm build` | "빌드해" |'
  return [
    '# 📋 한국어 명령어 가이드',
    '',
    '이 프로젝트에서 자주 쓰는 명령어입니다.',
    'AI(Claude/Cursor)에게 한국어로 말해도 됩니다.',
    '',
    '## 새 프로젝트 시작',
    '',
    '| 하고 싶은 것 | 터미널 명령 | AI에게 말하기 |',
    '|-------------|-----------|------------------|',
    '| 새 프로젝트 시작 (올인원) | `vhk start` | "새 프로젝트 시작해줘" |',
    '| 기술 스택을 바로 확정 | `vhk start --stack "Vite, React, TypeScript"` | "이 기술 스택으로 시작해줘" |',
    '',
    '> `vhk start` 하나로 `git init` + 문서 생성 + Cursor MCP 등록 + AI 컨텍스트 생성을 한 번에 처리합니다.',
    '> `--stack`을 지정하면 기술 스택을 확정하고, 미지정하면 자동 감지·유형 프리셋을 후보로 기록해 첫 세션에서 확인합니다.',
    '',
    '## 도움말',
    '',
    '| 범위 | 명령 | 표시 내용 |',
    '|------|------|----------|',
    '| 기본 명령 | `vhk --help` 또는 `vhk help` | 코딩 하네스 중심 |',
    '| 전체 명령 | `vhk help --all` | 마케팅·커머스 명령까지 전부 |',
    '',
    '## 매일 쓰는 명령어',
    '',
    '| 하고 싶은 것 | 터미널 명령 | AI에게 말하기 |',
    '|-------------|-----------|------------------|',
    '| 저장 | `vhk save` | "저장해" |',
    '| 오늘 정리 | `vhk 정리` | "오늘 한 일 정리해" |',
    '| 규칙 점검 | `vhk 점검` | "규칙 점검해" |',
    '| 보안 스캔 | `vhk 보안 scan` | "보안 스캔 돌려" |',
    buildTestRow,
    '| 배포 | `vhk 배포` | "배포해" |',
    '',
    '## 환경 점검',
    '',
    '```bash',
    'vhk doctor',
    '```',
    '',
    '---',
    '*Generated by `vhk init` — 수정해도 됩니다*',
  ].join('\n')
}
