export function CUSTOMIZATION_HOOK_TEMPLATE(): string {
  return [
    "import { existsSync } from 'node:fs'",
    "import { join } from 'node:path'",
    '',
    'try {',
    "  const vhk = join(process.cwd(), '.vhk')",
    "  const needs = existsSync(join(vhk, 'NEEDS_CUSTOMIZATION'))",
    "  const done = existsSync(join(vhk, 'customization-done'))",
    '  if (needs && !done) {',
    '    const additionalContext = [',
    "      '이 프로젝트는 방금 vhk init 으로 생성됐고 아직 도메인 커스터마이징이 안 됐다(.vhk/NEEDS_CUSTOMIZATION 존재).',",
    "      '지금 사용자와 짧은 인터뷰를 진행해라. 고정 체크리스트를 그대로 읽지 말고, 이 프로젝트 성격에 맞게 질문을 다듬어 아래 4가지를 파악해라:',",
    "      '  1) 핵심 도메인 규칙 — 이 도메인에서 반드시 지켜야 하는 계산·절차·불변식',",
    "      '  2) 절대 금지 행동 — 해서는 안 되는 것(데이터 삭제·무단 외부 전송 등)',",
    "      '  3) 연동할 외부 API·서비스 — 무엇과 어떻게 연동하는지',",
    "      '  4) 데이터 민감도 — 개인정보·비밀키 등 취급 주의 데이터',",
    "      '답변은 RULES.md 의 `## 도메인 규칙` 섹션 하나에 정리해라(없으면 새로 만들고, 네 주제는 ### 하위 제목으로 나눠도 된다). 이 제목이라야 vhk sync 가 .cursorrules·CLAUDE.md 를 포함한 모든 도구 파일로 전파한다.',",
    "      '정리한 뒤 vhk sync 를 실행해라.',",
    "      '한 번에 하나씩 자연스럽게 물어보고, 사용자가 건너뛰길 원하면 존중해라.',",
    "      '인터뷰를 끝냈든, 사용자가 건너뛰기를 택했든 — 어느 쪽이든 .vhk/customization-done 파일을 생성해라(내용은 비워도 됨).',",
    "      '이 마커를 안 만들면 다음 세션마다 이 안내가 계속 다시 뜬다 — 건너뛴 경우에도 반드시 만들어서 재넛지를 막아라.',",
    "    ].join('\\n')",
    '    console.log(JSON.stringify({ hookSpecificOutput: { hookEventName: \'SessionStart\', additionalContext } }))',
    '  }',
    '} catch {',
    '  // fail-open: 어떤 내부 오류도 세션 시작을 막지 않는다(무출력 → 넛지 없음).',
    '}',
    'process.exit(0)',
    '',
  ].join('\n');
}
