import inquirer from 'inquirer'
import chalk from 'chalk'
import fs from 'node:fs'
import path from 'node:path'
import { getSessionDiff, getRecentCommits, isGitRepo } from '../lib/git.js'

export type RecapOptions = {
  since?: string
}

export async function recap(options: RecapOptions = {}) {
  console.log(chalk.bold('\n📝 VHK RECAP — 세션 기록 자동 생성\n'))

  if (!(await isGitRepo())) {
    console.log(chalk.red('❌ Git 레포가 아닙니다. git init 먼저 실행하세요.'))
    return
  }

  console.log(chalk.dim('📊 Git 변경사항 분석 중...\n'))
  const diff = await getSessionDiff(options.since)
  const commits = await getRecentCommits(10, options.since)

  if (diff.filesChanged === 0 && commits.length === 0) {
    console.log(chalk.yellow('⚠️ 변경사항이 없습니다. 커밋하거나 파일을 수정한 후 다시 시도하세요.'))
    return
  }

  console.log(chalk.bold('📊 변경 요약:'))
  console.log(`  파일: ${chalk.cyan(String(diff.filesChanged))}개 변경`)
  console.log(`  추가: ${chalk.green('+' + diff.insertions)} / 삭제: ${chalk.red('-' + diff.deletions)}`)

  if (diff.files.length > 0) {
    console.log(chalk.dim('\n  변경 파일:'))
    diff.files.slice(0, 15).forEach(f => {
      const icon = f.status === 'new' ? chalk.green('🆕')
        : f.status === 'deleted' ? chalk.red('🗑️')
        : chalk.yellow('✏️')
      console.log(`  ${icon} ${f.file}`)
    })
    if (diff.files.length > 15) {
      console.log(chalk.dim(`  ... 외 ${diff.files.length - 15}개`))
    }
  }

  if (commits.length > 0) {
    console.log(chalk.dim('\n  최근 커밋:'))
    commits.slice(0, 5).forEach(c => {
      console.log(chalk.dim(`  • ${c.message}`))
    })
  }

  console.log('')
  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'summary',
      message: '📝 이번 세션에서 뭘 했나요? (1~3줄)',
    },
    {
      type: 'input',
      name: 'decisions',
      message: '🧭 내린 결정이 있나요? (없으면 Enter)',
      default: '없음',
    },
    {
      type: 'input',
      name: 'nextTodo',
      message: '⏭️ 다음 세션에서 할 일은?',
    },
    {
      type: 'input',
      name: 'blockers',
      message: '🚧 블로커가 있나요? (없으면 Enter)',
      default: '없음',
    },
  ])

  const today = new Date().toISOString().split('T')[0]
  const logDir = path.join(process.cwd(), 'docs', 'log')
  if (!fs.existsSync(logDir)) fs.mkdirSync(logDir, { recursive: true })

  const existing = fs.readdirSync(logDir).filter(f => f.startsWith(today))
  const sessionNum = existing.length + 1
  const fileName = `${today}-session-${sessionNum}.md`
  const filePath = path.join(logDir, fileName)

  const fileList = diff.files
    .map(f => `| ${f.file} | ${f.status} |`)
    .join('\n')

  const commitList = commits
    .slice(0, 10)
    .map(c => `- \`${c.hash.slice(0, 7)}\` ${c.message}`)
    .join('\n')

  const content = [
    `# 세션 로그 — ${today} #${sessionNum}`,
    '',
    '## 작업 요약',
    answers.summary,
    '',
    '## 결정 사항',
    answers.decisions,
    '',
    '## 다음 할 일',
    answers.nextTodo,
    '',
    '## 블로커',
    answers.blockers,
    '',
    '## 변경 파일',
    `총 ${diff.filesChanged}개 파일 (+${diff.insertions} -${diff.deletions})`,
    '',
    '| 파일 | 상태 |',
    '|------|------|',
    fileList,
    '',
    '## 커밋 로그',
    commitList || '(커밋 없음)',
    '',
    '---',
    `*Generated by \`vhk recap\` at ${new Date().toISOString()}*`,
  ].join('\n')

  fs.writeFileSync(filePath, content, 'utf-8')

  console.log(chalk.green.bold('\n✅ 세션 로그 생성 완료!'))
  console.log(chalk.dim(`  📄 ${path.relative(process.cwd(), filePath)}`))

  const claudeMdPath = path.join(process.cwd(), 'CLAUDE.md')
  if (fs.existsSync(claudeMdPath)) {
    const { updateClaude } = await inquirer.prompt([{
      type: 'confirm',
      name: 'updateClaude',
      message: 'CLAUDE.md "현재 상태" 섹션도 업데이트할까요?',
      default: true,
    }])

    if (updateClaude) {
      let claudeContent = fs.readFileSync(claudeMdPath, 'utf-8')
      claudeContent = claudeContent.replace(
        /- \*\*마지막 업데이트:\*\*.*/,
        `- **마지막 업데이트:** ${today}`
      )
      claudeContent = claudeContent.replace(
        /- \*\*다음 액션:\*\*.*/,
        `- **다음 액션:** ${answers.nextTodo}`
      )
      fs.writeFileSync(claudeMdPath, claudeContent, 'utf-8')
      console.log(chalk.green('  ✅ CLAUDE.md 업데이트 완료'))
    }
  }

  console.log(chalk.dim(`\n💡 팁: git add docs/log/ && git commit -m "docs: session recap ${today}"\n`))
}
